import Head from 'next/head'

import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Process from '../components/Process'
import Work from '../components/Work'
import Services from '../components/Services'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className= 'w-[100%] bg-red-50'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full flex justify-center flex-col items-center relative'>
        <Navbar/>
        <Hero/>
        <Process/>
        <Work/>
        <Services/>
        <Contact/>
        <Footer/>
      </main>

      
    </div>
  )
}
